name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macosx:
    #runs-on: macos-latest
    # Marked as generally available https://github.com/actions/runner-images/issues/13739
    # Bur for some reason not promoted to `-latest`.
    runs-on: macos-26
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-node@main
    - run: npm install
    - run: npm test
    - run: ./build.sh
    - uses: actions/upload-artifact@main
      with:
        name: alfred-emoji.alfredworkflow
        path: alfred-emoji.alfredworkflow
